### ISSUE TITLE
Incomplete Manhattan plots 

### ISSUE THREAD

**Issue by MuBulut** [xiaolei-lab/rMVP#49] opened 2020-07-01 14:31 UTC
Hi,
I recently got this incomplete manhatten plot while running a rMVP script on a linux server (end of Chr 12 not mapped) This phenomenon does not occur when I am running the same script on my windows working station. 
Thanks in advance for the help.

![Solyc01g109520 MLM Rectangular-Manhattan dom](https://user-images.githubusercontent.com/67698282/86255693-b64b0300-bbb7-11ea-962c-08383ace1f8c.jpg)

**Comment by YinLiLin** [comment] 2020-07-02 05:35
Thanks for raising this issue, the problem has been fixed for the latest version on GitHub, please reinstall rMVP from GitHub and try again. If it still exists, please feed back here, we are pleasure to figure it out.

**Comment by MustafaBulutMPI** [comment] 2020-07-02 08:35
Thanks for the quick reply. Unfortunately, this do not solve the problem. However, rMVP version 0.99 gives the desired results on one server and not on another one. It seems a bit off, that while using the exact same script, the SNP density plot uses different coloration. 
![aa MLM Rectangular-Manhattan dom](https://user-images.githubusercontent.com/67698282/86336002-86e7d500-bc4f-11ea-9e82-fd4f47f36d95.jpg)
![Rectangular-Manhat_dom](https://user-images.githubusercontent.com/67698282/86336007-88190200-bc4f-11ea-84ce-6a252ba48325.jpg)

**Comment by YinLiLin** [comment] 2020-07-02 09:16
Thank you. It seems better than previous version, as the density bar can completely cover the chromosome. 
From the above figures, I am little confused which one is the output of the latest version of rMVP, I guess the first one should be. I have double checked the script of rMVP, the coloration of density bar is mandatorily fixed with ```c("darkgreen", "yellow", "red")```, but not in the previous version, I think this is the reason why they look different for the density bar between the two versions you compared. 
One more question, are those two Manhattan plots are come from different version of rMVP on the same trait?

**Comment by MustafaBulutMPI** [comment] 2020-07-02 09:23
You are right, the above one is from the version 1.0.2 and the lower one is based on version 0.99. The 2 Manhatten plots come from different traits and different versions of rMVP, just to visualize the problem.

**Comment by MustafaBulutMPI** [comment] 2020-07-06 10:07
I wanted to ask if there is a way to work-around for this issue. Below is the rMVP script that I run.

`library(rMVP)
library(data.table)

VP.Data(fileHMP = "Genome.hmp.txt",
         sep.hmp="\t",
         SNP.effect="Add",
         filePhe="phenotype.txt",
         sep.phe="\t",
         filePC='PC_file.txt',
         type.pc="double",
         sep.pc="\t",
         fileKin='Kinship.txt',
         type.kin="double",
         sep.kin="\t",
         out="mvp.hmp",
         priority="speed"
         
)



genotype <- attach.big.matrix("mvp.hmp.geno.desc")
Kinship <- attach.big.matrix("mvp.hmp.kin.desc")
Covariates <- attach.big.matrix('mvp.hmp.pc.desc')

map <- fread("mvp.hmp.map" , head = TRUE)


met_all <- read.table("phenotype.txt",header = T)
name <- colnames(met_all)


for(i in 2:length(name)){
  gc() 
    imMVP <- MVP(
    phe=met_all[, c(1,i)],
    geno=genotype,
    map=map,
    K=Kinship,
    CV.MLM=Covariates,
    priority="speed",
    ncpus=200,
    vc.method="EMMA",
    method.bin="EMMA",
    threshold=0.01,
    method="MLM",
    col=c("steelblue4","cyan3"),
    memo='dom',
    file.output = T
    )
    
}
`

**Comment by MustafaBulutMPI** [comment] 2020-07-23 08:59
Hi,
I just tried a new run with the dev version 1.0.3
The strange thing that we observed is, that the manhattenplots randomly stop to plot....., where the SNP density plot visualizes all Chromosmal positions, with the accurate SNP density...

![Solyc01g109520 MLM SNP-Density dom](https://user-images.githubusercontent.com/67698282/88268936-7fa66b00-ccd3-11ea-86fe-21a12f90f426.jpg)

![Solyc01g109520 MLM Rectangular-Manhattan dom](https://user-images.githubusercontent.com/67698282/88268839-5a196180-ccd3-11ea-97ab-96a022dd874a.jpg)

**Comment by YinLiLin** [comment] 2020-07-24 03:36
Did you check if the p-values for the SNPs at the end of chromosome 12 are normal? how about visualising the GWAS results by function of ```MVP.Report```?

**Comment by MustafaBulutMPI** [comment] 2020-07-24 09:20
The problem is that the output .csv files are missing those regions as well, its not only the figure. The problem with the plot is basically a downstream error, originating from the missing p-values in the .csv result files.

**Comment by YinLiLin** [comment] 2020-07-24 10:34
Sounds strange, what's the meaning of "missing those regions"? are the SNPs in this region not included in the .csv file or just having p-values but in unexpected values?

**Comment by MustafaBulutMPI** [comment] 2020-07-24 10:37
the snps are included, but with an NA instead of a value

**Comment by YinLiLin** [comment] 2020-07-24 10:44
Did you check the polymorphism of those SNPs? to calculate MAF for example, the p-value would result in NAs if there is no polymorphism (maf=0).

**Comment by MustafaBulutMPI** [comment] 2020-07-24 10:59
The SNPs below MAF=5% are already filtered out.
There is a clear polymorphism in those SNPs.

**Comment by YinLiLin** [comment] 2020-07-24 11:19
Thank you, is this case only appearing for one trait or all traits? and do all individuals have a phenotypic value for this trait? sometimes if the phenotypic values of the individuals holding the minor genotype are missing, then those SNPs will be non-polymorphism, but despite that,  I am just wondering why such big number of SNPs in a continuous region can encounter the same problem.

**Comment by MustafaBulutMPI** [comment] 2020-07-24 11:24
it occurs for all traits in my phenotype file.
The strange part is, when I restart the script it stops at a different SNP around the end of Chr12 (see first manhattenplot I posted and the last one; in the first one it almost cover all of Chr12, however in the last one only the beginning of Chr12 is maped).

**Comment by YinLiLin** [comment] 2020-07-24 11:37
Yes, I see it. I guess the reason why it stops at a different SNPs when you ran the same script is due to the different version of rMVP you used. To figure out what it goes wrong on earth, it would be better to send me your data for debugging if you don't mind.

**Comment by MustafaBulutMPI** [comment] 2020-07-24 12:03
No, even if I use the same version it stops at different positions.
Also, if I run the script on a different server it fully covers all SNPs.
It might be that a specific version a required r package is needed to run it properly.
Sorry, but I cannot share the data because the genotype information is confidential.

**Comment by YinLiLin** [comment] 2020-07-24 12:43
From what you described, it seems to be not a such simple problem, only occurs rarely in specific situation. Rather than the certain potential matter in the source script of rMVP , it should be attributed more to the system environment of the server, more likely to the OpenMP (not very sure).

**Comment by MustafaBulutMPI** [comment] 2020-08-28 14:20
Hi I was just curious what the effect and se columns are in the GWAS result files.
I guess the se is the standard error of the model, but I was not sure.
Thanks in advance.

**Comment by XiaoleiLiuBio** [comment] 2020-08-29 08:51
The 'effect' and 'se' are the coefficient value and the corresponding standard error for each tested SNP, respectively. These two values can be used for summary statistics analysis.

**Comment by MustafaBulutMPI** [comment] 2020-09-22 07:15
Thanks a lot for your reply, I was curious about imputations in general in rMVP. Does rMVP impute missing values for traits ["NAs"]?

**Comment by XiaoleiLiuBio** [comment] 2020-09-23 01:09
The individuals with missing phenotypic records are removed in the statistical analysis.

**Comment by hyacz** [comment] 2020-09-23 06:21
I guess the reason for the incomplete Manhattan chart may come from the data format conversion from HMP to MVP. This issue was fixed in 1.0.4 (see https://github.com/xiaolei-lab/rMVP/commit/194317ccef91f09f3b71bae553b6724e8099a087). Have you tried the new version?

**Comment by MustafaBulutMPI** [comment] 2020-09-24 15:05
hi,
thanks again.
I just did two run with the new version on the servers.
The first one looked nice, [But I still Chr12 was missing]

![](https://rakete.mpimp-golm.mpg.de/file-upload/eSk3Qo5bAnhg4wzTw/G_30_179.035_0.525.MLM.Rectangular-Manhattan.dom.jpg)


The rerun however did result in the same error.


![](https://rakete.mpimp-golm.mpg.de/file-upload/7RQNwZMW8vXq6Cxfa/G_30_179.035_0.525.MLM.Rectangular-Manhattan.dom.jpg)

Somehow, it randomly stops processing the SNPs.....

**Comment by YinLiLin** [comment] 2020-09-29 06:25
The issue proposed by @hyacz is a bug of reading genotype data in VCF format, if your genotype is not stored in VCF format, just ignore it, otherwise, please start to retry the latest version of rMVP (1.0.4) from data transformation.

**Closed** 2023-03-31 03:40 UTC
